# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 11:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Economies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35, verbose_name='Type of state')),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField()),
                ('is_player_faction', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GovType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=35, verbose_name='Type of Government')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Powers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35, verbose_name='Type of state')),
            ],
        ),
        migrations.CreateModel(
            name='PowerStates',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35, verbose_name='Type of state')),
            ],
        ),
        migrations.CreateModel(
            name='Reserves',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35, verbose_name='Type of state')),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35, verbose_name='Type of state')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35, verbose_name='Type of state')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SuperPower',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35, verbose_name='Name of the Super Power')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35, verbose_name='Name of the_System')),
                ('type', models.CharField(max_length=35, verbose_name='Type of Government')),
                ('population', models.IntegerField()),
                ('is_populated', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField()),
                ('needs_permit', models.BooleanField(default=False)),
                ('power', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Powers')),
                ('power_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.PowerStates')),
                ('primary_economy_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Economies')),
                ('reserves', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Reserves')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Security')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.State')),
            ],
        ),
        migrations.CreateModel(
            name='SystemFactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecycle', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('Contr_Faction', models.BooleanField(default=False, verbose_name='Is Controling?')),
                ('influence', models.FloatField(verbose_name='Influence')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Faction')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.State')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.System')),
            ],
        ),
        migrations.AddField(
            model_name='faction',
            name='allegiance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.SuperPower'),
        ),
        migrations.AddField(
            model_name='faction',
            name='government',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.GovType'),
        ),
        migrations.AddField(
            model_name='faction',
            name='home_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.System'),
        ),
        migrations.AddField(
            model_name='faction',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.State'),
        ),
        migrations.AlterUniqueTogether(
            name='systemfactions',
            unique_together=set([('datecycle', 'system', 'faction')]),
        ),
        migrations.AlterIndexTogether(
            name='systemfactions',
            index_together=set([('datecycle', 'system', 'faction')]),
        ),
    ]
