# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 09:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170418_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='fState',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35, verbose_name='Type of state')),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SFHist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Datecycle', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('fInfluence', models.FloatField(verbose_name='Influence')),
                ('sFaction', models.BooleanField(default=False, verbose_name='Controling_Faction')),
                ('sPopulation', models.IntegerField()),
                ('fhState', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.fState')),
                ('sGovtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.GovType')),
            ],
        ),
        migrations.CreateModel(
            name='sState',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35, verbose_name='Type of state')),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='systemfaction',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='systemfaction',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='systemfaction',
            name='faction',
        ),
        migrations.RemoveField(
            model_name='systemfaction',
            name='state',
        ),
        migrations.RemoveField(
            model_name='systemfaction',
            name='system',
        ),
        migrations.RemoveField(
            model_name='system',
            name='type',
        ),
        migrations.AddField(
            model_name='system',
            name='govtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.GovType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='economy',
            name='name',
            field=models.CharField(max_length=35, verbose_name='Type of Economy'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.fState'),
        ),
        migrations.AlterField(
            model_name='power',
            name='name',
            field=models.CharField(max_length=35, verbose_name='Power Name'),
        ),
        migrations.AlterField(
            model_name='powerstate',
            name='name',
            field=models.CharField(max_length=35, verbose_name='System Power State'),
        ),
        migrations.AlterField(
            model_name='security',
            name='name',
            field=models.CharField(max_length=35, verbose_name='Type of Security'),
        ),
        migrations.AlterField(
            model_name='system',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.fState'),
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='SystemFaction',
        ),
        migrations.AddField(
            model_name='sfhist',
            name='sSecurity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Security'),
        ),
        migrations.AddField(
            model_name='sfhist',
            name='seconomy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Economy'),
        ),
        migrations.AddField(
            model_name='sfhist',
            name='sfhFaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Faction'),
        ),
        migrations.AddField(
            model_name='sfhist',
            name='sfhSystem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.System'),
        ),
        migrations.AddField(
            model_name='sfhist',
            name='shState',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.sState'),
        ),
        migrations.AddField(
            model_name='sfhist',
            name='spower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Power'),
        ),
        migrations.AddField(
            model_name='sfhist',
            name='spower_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.PowerState'),
        ),
        migrations.AlterUniqueTogether(
            name='sfhist',
            unique_together=set([('Datecycle', 'sfhSystem', 'sfhFaction')]),
        ),
        migrations.AlterIndexTogether(
            name='sfhist',
            index_together=set([('Datecycle', 'sfhSystem', 'sfhFaction')]),
        ),
    ]
