# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170425_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='economy',
            name='game_id',
            field=models.CharField(default=' ', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fstate',
            name='game_id',
            field=models.CharField(default=' ', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='govtype',
            name='game_id',
            field=models.CharField(default=' ', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='power',
            name='game_id',
            field=models.CharField(default=' ', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powerstate',
            name='game_id',
            field=models.CharField(default=' ', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserve',
            name='game_id',
            field=models.CharField(default=' ', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='security',
            name='game_id',
            field=models.CharField(default=' ', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sstate',
            name='game_id',
            field=models.CharField(default=' ', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superpower',
            name='game_id',
            field=models.CharField(default=' ', max_length=35),
            preserve_default=False,
        ),
    ]
