# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170425_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfhist',
            name='allegiance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.SuperPower'),
        ),
        migrations.AddField(
            model_name='system',
            name='allegiance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.SuperPower'),
        ),
    ]
