# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170425_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='population',
            field=models.BigIntegerField(null=True),
        ),
    ]
