# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170430_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sfhist',
            old_name='allegiance',
            new_name='sAllegiance',
        ),
        migrations.RenameField(
            model_name='sfhist',
            old_name='seconomy',
            new_name='sEconomy',
        ),
        migrations.RenameField(
            model_name='sfhist',
            old_name='spower',
            new_name='sPower',
        ),
        migrations.RenameField(
            model_name='sfhist',
            old_name='spower_state',
            new_name='sPower_state',
        ),
        migrations.RemoveField(
            model_name='sfhist',
            name='sPopulation',
        ),
    ]
