# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 21:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170501_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='FHist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Datecycle', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('fhInfluence', models.FloatField(null=True, verbose_name='Influence')),
                ('fhAllegiance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.SuperPower')),
                ('fhFaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Faction')),
                ('fhGovtype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.GovType')),
                ('fhState', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.fState')),
                ('fhSystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.System')),
            ],
        ),
        migrations.CreateModel(
            name='SHist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Datecycle', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('shAllegiance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.SuperPower')),
                ('shEconomy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Economy')),
                ('shFaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Faction')),
                ('shGovtype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.GovType')),
                ('shPower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Power')),
                ('shPower_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.PowerState')),
                ('shSecurity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Security')),
                ('shState', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.sState')),
                ('shSystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.System')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sfhist',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='sfhist',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='sfhist',
            name='fhState',
        ),
        migrations.RemoveField(
            model_name='sfhist',
            name='sAllegiance',
        ),
        migrations.RemoveField(
            model_name='sfhist',
            name='sEconomy',
        ),
        migrations.RemoveField(
            model_name='sfhist',
            name='sGovtype',
        ),
        migrations.RemoveField(
            model_name='sfhist',
            name='sPower',
        ),
        migrations.RemoveField(
            model_name='sfhist',
            name='sPower_state',
        ),
        migrations.RemoveField(
            model_name='sfhist',
            name='sSecurity',
        ),
        migrations.RemoveField(
            model_name='sfhist',
            name='sfhFaction',
        ),
        migrations.RemoveField(
            model_name='sfhist',
            name='sfhSystem',
        ),
        migrations.RemoveField(
            model_name='sfhist',
            name='shState',
        ),
        migrations.DeleteModel(
            name='SFHist',
        ),
        migrations.AlterUniqueTogether(
            name='shist',
            unique_together=set([('Datecycle', 'shSystem')]),
        ),
        migrations.AlterIndexTogether(
            name='shist',
            index_together=set([('Datecycle', 'shSystem')]),
        ),
        migrations.AlterUniqueTogether(
            name='fhist',
            unique_together=set([('Datecycle', 'fhSystem', 'fhFaction')]),
        ),
        migrations.AlterIndexTogether(
            name='fhist',
            index_together=set([('Datecycle', 'fhSystem', 'fhFaction')]),
        ),
    ]
