# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170502_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='primary_economy_id',
        ),
        migrations.AddField(
            model_name='system',
            name='primary_economy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Economy'),
        ),
    ]
